apiVersion: v1
kind: ServiceAccount
metadata:
  name: multi-networkpolicy
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multi-networkpolicy
rules:
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - multi-networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multi-networkpolicy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multi-networkpolicy
subjects:
- kind: ServiceAccount
  name: multi-networkpolicy
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multi-networkpolicy
  namespace: kube-system
  labels:
    tier: node
    app: multi-networkpolicy
    name: multi-networkpolicy
spec:
  selector:
    matchLabels:
      name: multi-networkpolicy
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: multi-networkpolicy
        name: multi-networkpolicy
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      serviceAccountName: multi-networkpolicy
      priorityClassName: system-node-critical
      containers:
      - name: multi-networkpolicy
        image: ghcr.io/k8snetworkplumbingwg/multi-networkpolicy:snapshot
        command:
        - /usr/bin/multi-networkpolicy-iptables
        args:
        - --host-prefix=/host
        - --container-runtime=crio
        - --run-dir=/var/lib/multinetworkpolicy
        resources:
          requests:
            cpu: "100m"
            memory: "80Mi"
          limits:
            cpu: "100m"
            memory: "80Mi"
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            - NET_ADMIN
            - SYS_PTRACE
        volumeMounts:
        - name: cni
          mountPath: /host/opt/cni/bin
        - name: cniconf
          mountPath: /host/etc/cni/net.d
        - name: multus-cniconf
          mountPath: /host/etc/cni/multus/net.d
        - name: run
          mountPath: /var/lib/multinetworkpolicy
          mountPropagation: Bidirectional
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cni
        hostPath:
          path: /opt/cni/bin
      - name: cniconf
        hostPath:
          path: /etc/cni/net.d
      - name: multus-cniconf
        hostPath:
          path: /etc/cni/multus/net.d
      - name: run
        hostPath:
          path: /var/lib/multinetworkpolicy
          type: DirectoryOrCreate
